/**
 * Content extraction types
 */

export interface ExtractedContent {
  title: string
  content: string
  textContent: string
  excerpt?: string
  byline?: string
  siteName?: string
  url: string
  length: number
  type: ContentType
}

export type ContentType = 'web' | 'pdf' | 'youtube' | 'video' | 'unknown'

export interface PDFContent {
  title: string
  content: string
  pageCount: number
  metadata?: PDFMetadata
}

export interface PDFMetadata {
  author?: string
  title?: string
  subject?: string
  creator?: string
  producer?: string
  creationDate?: string
  modificationDate?: string
}

export interface YouTubeSubtitle {
  text: string
  start: number
  duration: number
}

export interface YouTubeSubtitleTrack {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
  subtitles: YouTubeSubtitle[]
}

export interface VideoInfo {
  title: string
  url: string
  hasSubtitles: boolean
  subtitleTracks?: YouTubeSubtitleTrack[]
}

// Message action types for content script communication
export const ContentActions = {
  FETCH_PAGE_CONTENT: 'FETCH_PAGE_CONTENT',
  FETCH_TEXT_CONTENT: 'FETCH_TEXT_CONTENT',
  GET_PAGE_URL: 'GET_PAGE_URL',
  GET_VIDEO_INFO: 'GET_VIDEO_INFO',
  GET_YOUTUBE_SUBTITLES: 'GET_YOUTUBE_SUBTITLES',
} as const

export type ContentAction = (typeof ContentActions)[keyof typeof ContentActions]

export interface ContentMessage {
  action: ContentAction
  data?: unknown
}

export interface ContentResponse<T = unknown> {
  success: boolean
  data?: T
  error?: string
}
