name: Build Chrome Extension on Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug workspace
        run: ls -R

      - name: Install crx3
        run: npm install -g crx3

      - name: Create private key
        env:
          PRIVATE_KEY: ${{ secrets.EXTENSION_PRIVATE_KEY }}
        run: echo "$PRIVATE_KEY" > key.pem

      - name: Build OrangeSideBar.crx
        run: |
          crx3 --private-key=key.pem --zip chrome-extension.zip ./ # 替换 ./ 为实际路径
          mv extension.crx OrangeSideBar.crx

      - name: Upload OrangeSideBar.crx to Release
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.MINE_TOKEN }}
          release_id: ${{ github.event.release.id }}
          asset_path: OrangeSideBar.crx
          asset_name: OrangeSideBar.crx
          asset_content_type: application/x-chrome-extension
