name: Build Chrome Extension on Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 安装 crx3 工具
      - name: Install crx3
        run: npm install -g crx3

      # 创建私钥文件
      - name: Create private key
        env:
          PRIVATE_KEY: ${{ secrets.EXTENSION_PRIVATE_KEY }}
        run: echo "$PRIVATE_KEY" > key.pem

      # 先创建 zip 包，再生成 crx
      - name: Build Extension
        run: |
          # 先将所有文件打包成 zip
          zip -r chrome-extension.zip . -x "*.git*" "*.pem" "*.crx"

          # 使用 crx3 打包
          crx3 --private-key=key.pem --zip chrome-extension.zip

          # 重命名
          mv extension.crx OrangeSideBar.crx

      - name: Upload OrangeSideBar.crx to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MINE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./OrangeSideBar.crx
          asset_name: OrangeSideBar.crx
          asset_content_type: application/x-chrome-extension
