name: Build Chrome Extension on Release

on:
  release:s
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 安装 crx3 工具
      - name: Install crx3
        run: npm install -g crx3

      # 创建 .pem 文件
      - name: Create private key
        env:
          PRIVATE_KEY: ${{ secrets.EXTENSION_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > key.pem

      # 打包为 OrangeSideBar.crx
      - name: Build OrangeSideBar.crx
        run: |
          crx3 --private-key=key.pem --zip chrome-extension.zip ./ # 打包插件
          mv extension.crx OrangeSideBar.crx # 重命名为 OrangeSideBar.crx

      # 上传 OrangeSideBar.crx 到 Release
      - name: Upload OrangeSideBar.crx to Release
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.MINE_TOKEN }}
          release_id: ${{ github.event.release.id }}
          asset_path: OrangeSideBar.crx
          asset_name: OrangeSideBar.crx
          asset_content_type: application/x-chrome-extension
